services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prueba_practica_neoris
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_PORT=${DB_PORT}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on: [ ]

