spring:
  application:
    name: prueba-practica-neoris
  webflux:
    base-path: /prueba-practica-neoris
  r2dbc:
    url: r2dbc:mysql://${DB_URL}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_SCHEMA}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}